### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by bosgood** [owenosborn/ofEYESY#2]
Hi Owen,

I'm interested in contributing to the ofxLua mode on the EYESY, I was wondering if you'd be able to share your workflow for building and iterating on this code?

I've tried compiling it in-place on the EYESY, but it ultimately ends in virtual memory OOM errors. Some messing around in `raspi-config` let me get past those, but other errors eventually stop the compilation. Cross compilation seems possible (and would be way faster), but I haven't succeeded with that either (I'm running OSX, so it would probably involve a VM or Docker).

Things that I think would be interesting to help implement would be:
- feature parity with the Python version
- shader support
- Lua integration with additional openFrameworks addons such as physics engines, and animation libraries

Thanks for any help you can provide.

**Comment by critterandguitari** [comment]
Thanks for your interest in this project! 

We've been working with pi-gen (https://github.com/RPi-Distro/pi-gen) to automate the initial build process, and hoping the cross compiling does speed things up. However once the disk image is built with all the required software (e.g. openframeworks), compiling this project doesn't take much time and can be done directly on the EYESY / rPi.

For now, there is a disk image with everything installed that we use to develop on:

http://thepeacetreaty.org/eyesy/images/EYESY_oFLua_beta1.img.zip

**Comment by bosgood** [comment]
Thanks. I ended up getting everything to work by flashing the latest disk image, then doing this:

```bash
sudo mount -o remount,ro /
cd ~/EYESY_OS
git fetch
git checkout oflua
sudo systemctl restart eyesy-pd

cd ~/openFrameworks/apps/myApps/eyesy
# make any changes directly, use scp, or git pull from another repo
make
# then restart the video in the web GUI
```
